apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-standard
provisioner: rancher.io/local-path
reclaimPolicy: Delete
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer
